# -*- coding: utf-8 -*-
"""tarea_ruuf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11BZOrMhEPfpWEeVYdr0NEECeokOhuWrF
"""

def max_panels_amount(a: int, b: int, x: int, y: int) -> int:
    """
    Calcula la cantidad máxima de paneles solares que caben en un techo.

    Parámetros:
    a, b: int = Dimensiones del panel solar.
    x, y: int = Dimensiones del techo.

    Retorna -> int:
    El número máximo de paneles que se pueden colocar.
    """


    # Primera orientación

    first_fit_1 = x // b
    second_fit_1 = y // a

    total_1 = first_fit_1 * second_fit_1

    remaining_width_1 = x % b
    remaining_height_1 = y % a


    option1_extra_fit_1 = (remaining_width_1 // a) * (y // b)
    option2_extra_fit_1 = (remaining_height_1 // b) * (x // a)


    total_1 += (option1_extra_fit_1 + option2_extra_fit_1)



    # Segunda orientación

    first_fit_2 = x // a
    second_fit_2 = y // b

    total_2 = first_fit_2 * second_fit_2

    remaining_width_2 = x % a
    remaining_height_2 = y % b

    option1_extra_fit_2 = (remaining_width_2 // b) * (y // a)
    option2_extra_fit_2 = (remaining_height_2 // a) * (x // b)


    total_2 += (option1_extra_fit_2 + option2_extra_fit_2)


    return max(total_1, total_2)


# Tests
print(max_panels_amount(1, 2, 2, 4))  # Output: 4
print(max_panels_amount(2, 1, 5, 3))  # Output: 7
print(max_panels_amount(2, 2, 5, 3))  # Output: 2
print(max_panels_amount(1, 1, 5, 3))  # Output: 15
print(max_panels_amount(3, 1, 5, 3))  # Output: 5
print(max_panels_amount(2, 2, 1, 10))  # Output: 0